name: e2e tests on Mac M1

on:
  push:
    branches:
      - test-backup


jobs:

  e2e-tests:
    timeout-minutes: 45
    runs-on: [self-hosted, macos-latest, arm64]
    env:
      M1: 1
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Install dependencies
        run: npm ci
        #The next 2 steps are a workaround for an unexpected failure in launching electron before running e2e tests
        #Such failure is addressed in issue #2915
      - name: add tools to PATH
        run: |
          mkdir -p ~/.rd/bin
          cp -rf ~/actions-runner/_work/rancher-desktop/rancher-desktop/resources/darwin/bin/ ~/.rd/bin/
          export PATH="~/.rd/bin:$PATH"
      - name: Run Rancher Desktop in dev
        run: |
          npm run dev --no-modal-dialogs &
          sleep 300
          ~/.rd/bin/rdctl shutdown
          wait
      - name: Run e2e Tests
        continue-on-error: false
        run: npm run test:e2e
      - name: Failed tests
        if: failure()
        run: mkdir -p ./e2e/reports
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
      - name: Cleanup test environment
        run: |
          #set -x
          cd $HOME/Library
          pushd Logs/rancher-desktop
          for x in *.log ; do
           echo -n '' > $x
          done
          popd
          rm -fr "Application Support/rancher-desktop"
          rm -fr Preferences/rancher-desktop
          rm -fr Caches/rancher-desktop/k3s-versions.json
          cd /usr/local/bin
          for x in helm kim kubectl nerdctl docker ; do
           if [[ -L $x ]] ; then # && $(readlink $x):]] ; then
           rm -f $x
           fi
          done
          case "${1:-}" in
          -sudo) ;;
          --sudo) ;;
          *)
          # echo "Delete the sudo lima files"
          sudo rm -fr /private/var/run/rancher-desktop-lima
          sudo rm -f /private/etc/sudoers.d/zzzzz-xrancher-desktop-lima
          sudo rm -fr /opt/rancher-desktop
          ;;
          esac
        if: always()
      - name: End stray processes
        run: |
          for x in nuxt qemu ; do
           echo $x
           ps auxww | grep $x
          done
          ps auxww | grep rancher | grep -vi -e goland
        if: always()


