name: e2e tests on Windows

on:
  push:
    branches:
        test-backup

jobs:

  e2e-tests:
    timeout-minutes: 45
    runs-on: [self-hosted, x64, win11]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Install dependencies
        run: npm ci
        #The next 2 steps are a workaround for an unexpected failure in launching electron before running e2e tests
        #Such failure is addressed in issue #2915
      - name: add tools to PATH
        run: |
          File "/oname=$PLUGINSDIR\add-to-path.ps1" "${BUILD_RESOURCES_DIR}\add-to-path.ps1"
          nsExec::ExecToLog 'powershell.exe \
          -NoProfile -NonInteractive -ExecutionPolicy RemoteSigned \
          -File "$PLUGINSDIR\add-to-path.ps1" "$INSTDIR"'
          Pop $R0
      #- name: Run Rancher Desktop in dev
      #  run: |
      #    npm run dev -- --no-modal-dialogs &
      #   sleep 200
      #    $HOME/.rd/bin/rdctl shutdown
      #    wait
      - name: Run e2e Tests
        continue-on-error: false
        run: npm run test:e2e
      - name: Failed tests
        if: failure()
        run: mkdir -p ./e2e/reports
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
      - name: Cleanup test environment
        run: |
          # Uninstall Priviliged Service
          File "/oname=$PLUGINSDIR\uninstall-privileged-service.ps1" "${BUILD_RESOURCES_DIR}\uninstall-privileged-service.ps1"
          nsExec::ExecToLog 'powershell.exe \
          -NoProfile -NonInteractive -ExecutionPolicy RemoteSigned \
          -File "$PLUGINSDIR\uninstall-privileged-service.ps1"'
          Pop $R0
          # Remove the bin directory from the PATH
          File "/oname=$PLUGINSDIR\remove-from-path.ps1" "${BUILD_RESOURCES_DIR}\remove-from-path.ps1"
          nsExec::ExecToLog 'powershell.exe \
          -NoProfile -NonInteractive -ExecutionPolicy RemoteSigned \
          -File "$PLUGINSDIR\remove-from-path.ps1" "$INSTDIR"'
          Pop $R0
          Remove-Item $HOME/AppData/Local/rancher-desktop -Recurse -Force
          Remove-Item $HOME/AppData/Local/rancher-desktop-updater -Recurse -Force
          Remove-Item $HOME/AppData/Roaming/rancher-desktop -Recurse -Force
          Remove-Item '$HOME/AppData/Local/Programs/Rancher Desktop' -Recurse -Force
        if: always()
      #- name: End stray processes
      #  run: |
      #    for x in nuxt qemu ; do
      #     echo $x
      #     ps auxww | grep $x
      #    done
      #   ps auxww | grep rancher | grep -vi -e goland
      #  if: always()
